### ISSUE TITLE
Forerunner 235 doesn't show HR data

### ISSUE THREAD

**Issue by HookyQR** [HookyQR/TidyWatch#2]
Exception logging added for this issue. If this issue is affecting you on version `0.1.5` on the FR235 please upload a copy of your `/GARMIN/APPS/LOGS/CIQ_LOG.txt` file.

**Comment by ajesler** [comment]
I deleted the `/GARMIN/APPS/LOGS/CIQ_LOG.txt`, unplugged the watch, waited till it displayed the TidyWatch face, and then plugged it back in and copied the `CIQ_LOG.txt` file off it. 

```
ERROR: Circular Dependency Error
DETAILS: 
STORE_ID: 8ac785e1628b46e5b4efc7d43ae159ab
CALLSTACK:

ERROR: Circular Dependency Error
DETAILS: 
STORE_ID: 8ac785e1628b46e5b4efc7d43ae159ab
CALLSTACK:
```

**Comment by HookyQR** [comment]
Cheers AJ, that's odd, but *probably* isn't the problem, it may be the app/view connection that it's linking there. Can you leave the watch face running for at least 3 minutes. That way the HR history should return as valid at some point during that period.

**Comment by HookyQR** [comment]
getHeartRateHistory doesn't accept a duration like it should. Working around with an 'approximate' 4 hours (180 samples for the ~80 samples per second).
