### ISSUE TITLE
Strange artefact on Fenix3HR

### ISSUE THREAD

**Issue by retrorich75** [HookyQR/TidyWatch#3]
Great watch face but I have a strange artefact on the watch face after some time, I'll add a link to image.

**Comment by retrorich75** [comment]
Image here https://github.com/retrorich75/commonfiles/blob/master/IMG_4880.JPG

**Comment by HookyQR** [comment]
Weird. It's a background fill issue. I should be able to get rid of that tonight. What watch do you have that on there?

**Comment by retrorich75** [comment]
Fenix 3 HR

**Comment by HookyQR** [comment]
About to push a fix for this and the FR235 issue.

**Comment by retrorich75** [comment]
Perfect HookyQR just home and updated, artifact cleaned up. FYI I had to set a different watch face and then do the update but the settings were defaulted i.e. The seconds came back which I had previously disabled, maybe do a check for previously saved settings file ??

**Comment by HookyQR** [comment]
Damn, sorry, that was my fault. I'd changed the app id at one point and forgot to change it back. I won't do that again. The saved settings are always reloaded, as long as the app id is the same. Oops.
